### ISSUE TITLE
Trying to cheat in items with a lot of nbt will result in player getting disconnected

### ISSUE THREAD

**Issue by Patbox** [emilyploszaj/emi#299] opened 2023-09-01 07:23 UTC
![image](https://github.com/emilyploszaj/emi/assets/39821509/9b9a9fac-7590-4d14-a10b-98ac73d5875b)

Version: 1.0.19+1.20.1+fabric

EMI isn't installed on the server.

Caused by this part of code not checking the length of the string, as vanilla limits read/write to 256:
https://github.com/emilyploszaj/emi/blob/1.20/xplat/src/main/java/dev/emi/emi/screen/EmiScreenManager.java#L1159

**Comment by emilyploszaj** [comment] 2023-09-02 23:43
This is a duplicate of #221, which really should be fixed soon.

**Closed as not planned by emilyploszaj** 2023-09-02 23:43 UTC
