### ISSUE TITLE
recipe tree and "love" button sometimes don't show

### ISSUE THREAD

**Issue by JieningYu** [emilyploszaj/emi#6] opened 2022-06-10 05:50 UTC
<img width="533" alt="image" src="https://user-images.githubusercontent.com/61787533/172999225-c81e3b8c-5737-47c9-9f6c-d209dd14b04e.png">

**Comment by LemmaEOF** [comment] 2022-06-10 05:59
This is likely because all outputs are only by chance, and not guaranteed. EMI doesn't like to do calculations for results based on RNG for trees.

**Comment by JieningYu** [comment] 2022-06-10 06:05
Is there any plans/solutions?

**Comment by JieningYu** [comment] 2022-06-10 15:02
So will chanced recipe output be in a medium part of a tree?

**Comment by emilyploszaj** [comment] 2022-06-10 15:05
In the future they will be able to show up in the middle as long as the chance is not on the *required* output. If possible, I might also attempt to allow trees with chanced outputs to form without counting costs, as well, so they can be fully used.

**Comment by emilyploszaj** [comment] 2022-07-31 18:34
Gonna close this as it's a future feature expansion and there is no proper bug that needs fixing, works as intended for now.

**Closed by emilyploszaj** 2022-07-31 18:34 UTC
