### ISSUE TITLE
[1.19.2] [Forge] Creative menu search crashes with EMI, JEI and ModernFix installed

### ISSUE THREAD

**Issue by Laton95** [emilyploszaj/emi#179] opened 2023-05-29 07:40 UTC
This might be a bit of a wild one, but the creative search menu crashes when searching with this combination of mods installed. It is something to do with the mixins ModernFix makes, specifically with it's perf.blast_search_trees module.

I do not know if this should be fixed on EMI's side or ModernFix's side, but here is the crash report:

https://mclo.gs/TXQWHCt

**Comment by SiverDX** [comment] 2023-05-29 08:05
See https://github.com/emilyploszaj/emi/issues/177
ModernFix already adressed it

**Comment by emilyploszaj** [comment] 2023-05-29 16:05
This is a duplicate of #177 and it seems like ModernFix has addressed the issue, nothing EMI can do to resolve this.

**Closed as completed by emilyploszaj** 2023-05-29 16:05 UTC
