### ISSUE TITLE
Unable to scroll batch size in receipe tree when it is 1.

### ISSUE THREAD

**Issue by IJustWantANamePlease** [emilyploszaj/emi#41] opened 2022-07-24 17:13 UTC
As the topic stated, in receipe tree, when batch size is 1, it cannot be changed by scrolling, but shift + scrolling still works. When it is greater than 1 normal scrolling functions normally.

**Comment by emilyploszaj** [comment] 2022-07-24 17:16
What mods do you have installed? I can't reproduce this in 1.18.2 or 1.19 with only Create and Botania at most

**Comment by IJustWantANamePlease** [comment] 2022-07-24 17:56
I disabled all mods except EMI andd fabric API but this still exists, not sure what is the cause.
I am using:
Minecraft 1.18.2
Fabric 0.14.7
Fabric API 0.51.1

**Comment by emilyploszaj** [comment] 2022-07-24 17:58
What system specs are you using? OS, are you using a normal mouse or a trackpad, etc?

**Comment by IJustWantANamePlease** [comment] 2022-07-24 18:03
I'm using Windows 10 and a bluetooth mouse, but trackpad also does not work.
When discrete scrolling is disabled it can be changed when I scroll really fast, but can't work at all when it is enabled.

**Comment by emilyploszaj** [comment] 2022-07-24 18:19
Interesting, well, I'll look into this, thanks for the report

**Comment by emilyploszaj** [comment] 2022-08-02 02:13
Fixed in 0.3.1

**Closed by emilyploszaj** 2022-08-02 02:13 UTC

**Comment by IJustWantANamePlease** [comment] 2022-08-08 09:14
Umm... I tested the 1.19 version and this is completely fixed, but with 1.18.2 the behaviour actually becomes stranger...

If discrete scrolling is toggled off, scrolling is normal;
but if it's turned on then it becomes unscrollable (not with fast scrolling anymore).
More importantly, in my case, shift scrolling is broken in 0.3.1. It no longer scrolls 16 at a time, the number ranges from below 10 to somewhere around 30, regardless of discrete scrolling.

Using Fabric 0.14.8 + Fabric API 0.58.0.
