### ISSUE TITLE
Exception when add mod "eldritch"

### ISSUE THREAD

**Issue by ghost** [emilyploszaj/emi#213] opened 2023-06-13 06:38 UTC
After adding the mod "eldritch mobs 1.12.11" to the latest version, there was a crash when join in the game: Internal Exception: java. lang. NoClassDefFoundError: dev/emi/emi/EmiReloadManager

**Comment by emilyploszaj** [comment] 2023-06-13 06:41
Duplicate of #182 fix is there

**Closed as completed by emilyploszaj** 2023-06-13 06:41 UTC
