### ISSUE TITLE
Game crash when opening graves with the graves mod

### ISSUE THREAD

**Issue by gamma-02** [emilyploszaj/emi#541] opened 2024-05-19 19:33 UTC
This issue occurs on my server when players try to open graves made with the Universal Graves mod, [https://modrinth.com/mod/universal-graves](https://modrinth.com/mod/universal-graves).

Crash logs:
https://mclo.gs/km8xAvR

**Comment by emilyploszaj** [comment] 2024-05-19 21:47
Duplicate of #530, going to get worked on

**Closed as completed by emilyploszaj** 2024-05-19 21:47 UTC
