### ISSUE TITLE
[Feature Request] REI Style Collapsible Entries

### ISSUE THREAD

**Issue by ThePansmith** [emilyploszaj/emi#676] opened 2024-08-30 13:24 UTC
The ability to create folders and collapse various items (spawn eggs, enchanted books, etc) into folders, along with [KJS support](https://wiki.latvian.dev/books/kubejs-legacy/page/rei-integration).

**Comment by emilyploszaj** [comment] 2024-08-31 02:49
Duplicate of #171

**Closed as completed by emilyploszaj** 2024-08-31 02:49 UTC
