### ISSUE TITLE
[FEATURE REQUEST] hide corner buttons

### ISSUE THREAD

**Issue by LTCatt** [emilyploszaj/emi#520] opened 2024-04-23 15:32 UTC
![image](https://github.com/emilyploszaj/emi/assets/40348278/60a4e35e-53ca-479c-8d2d-aff6410533fb)

Is there a way to hide those two buttons?

**Comment by emilyploszaj** [comment] 2024-06-17 01:36
This is a duplicate of #446

**Closed as completed by emilyploszaj** 2024-06-17 01:36 UTC
Labels: safe, thaumiel
