### ISSUE TITLE
`Duplicate key org.betterx.bclib.integration.emi.EMIAnvilRecipeCategory@20a49a8c (attempted merging values [] and [])`

### ISSUE THREAD

**Issue by SettingDust** [emilyploszaj/emi#204] opened 2023-06-04 04:50 UTC
```
java.lang.IllegalStateException: Duplicate key org.betterx.bclib.integration.emi.EMIAnvilRecipeCategory@20a49a8c (attempted merging values [] and [])
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.emi.emi.api.EmiApi.displayAllRecipes(EmiApi.java:118)
	at dev.emi.emi.screen.RecipeScreen.method_25402(RecipeScreen.java:411)
```

[crash-2023-06-04_12.46.46-client.txt](https://github.com/emilyploszaj/emi/files/11644789/crash-2023-06-04_12.46.46-client.txt)

**Comment by emilyploszaj** [comment] 2023-06-04 17:57
This is a duplicate of #191

**Closed as completed by emilyploszaj** 2023-06-04 17:57 UTC
