### ISSUE TITLE
Search doesn't work with left-sided index bar

### ISSUE THREAD

**Issue by Disketaa** [emilyploszaj/emi#720] opened 2024-09-29 21:06 UTC
![image](https://github.com/user-attachments/assets/bac9fdf7-f614-4183-99c7-dc61daf9039b)

The left side doesn't show my search result (cactus)

**Comment by emilyploszaj** [comment] 2024-09-29 22:31
This is a duplicate of #377

**Closed as completed by emilyploszaj** 2024-09-29 22:31 UTC
