### ISSUE TITLE
[Suggestion] Adding Custom Pages / Multiple Favorite Pages

### ISSUE THREAD

**Issue by Mangraz** [emilyploszaj/emi#457] opened 2024-03-08 18:37 UTC
Being able to make custom pages to show on the sidebar would be a great help with organizing, e. g. being able to create a second Favorite page to hold any recipe relevant for a specific project.

**Comment by emilyploszaj** [comment] 2024-03-09 02:04
This is a duplicate of #62, something I'd like to add eventually.

**Closed as not planned by emilyploszaj** 2024-03-09 02:04 UTC
