### ISSUE TITLE
Shows all synthesizable recipes, not just the recipes that can currently be synthesized

### ISSUE THREAD

**Issue by qizri** [emilyploszaj/emi#506] opened 2024-04-08 08:11 UTC
Add a new label page, shows all synthesizable items, and for those items that can't be synthesized at the moment, mark it with a red background

**Comment by emilyploszaj** [comment] 2024-04-14 19:33
This is a duplicate of #18, the craftable sidebar already exists otherwise.

**Closed as completed by emilyploszaj** 2024-04-14 19:33 UTC

**Comment by qizri** [comment] 2024-04-15 02:10
As far as I've researched, at the moment it will only show items that can be synthesized, and by that I mean: for example, when I get a piece of wood, it shows all the items it's participating in the synthesis of, even though at the moment we're lacking any other items that participate in the synthesis. For those items that cannot be synthesized at the moment, mark it with a red.
