### ISSUE TITLE
Items from Craftables page get cheated anyway instead of getting crafted.

### ISSUE THREAD

**Issue by Lgmrszd** [emilyploszaj/emi#202] opened 2023-06-03 13:52 UTC
Not sure if this is intended, but with cheat mode enabled (and using similar keybinds for cheat and crafting actions), behavior is not consistent when trying to quick craft items from Craftables page. This also applies to synthetic favorites and favorites with associated recipes.

Suggestion related to this: I think config option to limit cheat mode only to some panels or some pages (for example Index) would be nice.

**Comment by emilyploszaj** [comment] 2023-08-08 22:07
I think I'm going to close this as intended behavior, the order of these two options on overlapping binds is ambiguous on which way would cause more confusion, ideally I think different binds should be used.

**Closed as completed by emilyploszaj** 2023-08-08 22:07 UTC
