### ISSUE TITLE
Crash when middle clicking and scrolling at the same time on the favorites bar

### ISSUE THREAD

**Issue by snowtest-sled** [emilyploszaj/emi#75] opened 2022-08-28 22:55 UTC

**Comment by emilyploszaj** [comment] 2022-08-29 00:34
Do you have a crash log I can look at? I'm unable to reproduce this

**Comment by snowtest-sled** [comment] 2022-08-29 01:04
https://0.0g.gg/?f4df25c5426c20e7#FyDN67hsF4Djw4GSgosmKGc6Q5Mpep6gHKk7EXSZpqVr

**Comment by snowtest-sled** [comment] 2022-08-29 01:06
https://0.0g.gg/?b7c0ff0fec085571#2wpKQJcU2B3sXbvLrHususvT5MGHqWWgm3wigsrufMdL

**Comment by emilyploszaj** [comment] 2022-09-03 23:49
Fixed in 0.4.0

**Closed by emilyploszaj** 2022-09-03 23:49 UTC
Labels: keter
