### ISSUE TITLE
Unknown mod breaks craft to inventory

### ISSUE THREAD

**Issue by Xiarno** [emilyploszaj/emi#393] opened 2023-12-30 03:10 UTC
I added EMI to ATM9. While trying to craft to inventory, clicking once put the amount of material in the crafting bench but doesn't go into the inventory. I need to click a second time for it to work but then it craft twice the amount required.

**Comment by emilyploszaj** [comment] 2023-12-30 03:22
I've noticed this in the past but only in heavily modded packs. It works fine in vanilla. If you find out what mod is causing this issue I can look into it.

**Comment by Xiarno** [comment] 2023-12-30 03:53
Is there a way to log what happens?
I don't really want to inspect all 400 mods.

**Comment by emilyploszaj** [comment] 2023-12-30 04:07
Nope, this is an unknown issue the only solution is bisecting and manually testing.

**Comment by Xiarno** [comment] 2023-12-30 04:11
Dang :/

**Comment by emilyploszaj** [comment] 2024-01-12 23:21
I've discovered Fast Workbench is the cause (or one of the causes) of this. There's nothing EMI can do, and the "Fast" mods are notoriously incompatible with other mods, so unfortunately I'll have to close this issue.

**Closed as completed by emilyploszaj** 2024-01-12 23:21 UTC

**Comment by Xiarno** [comment] 2024-01-12 23:48
> I've discovered Fast Workbench is the cause (or one of the causes) of this. There's nothing EMI can do, and the "Fast" mods are notoriously incompatible with other mods, so unfortunately I'll have to close this issue.

What even does Fast Workbench do? It's in every modpack I play but I don't get what it does exactly.

**Comment by fzzyhmstrs** [comment] 2024-01-12 23:52
> > I've discovered Fast Workbench is the cause (or one of the causes) of this. There's nothing EMI can do, and the "Fast" mods are notoriously incompatible with other mods, so unfortunately I'll have to close this issue.
> 
> What even does Fast Workbench do? It's in every modpack I play but I don't get what it does exactly.

It aims to improve the performance of crafting, especially shift-crafting stacks of things, but evidently introduces it's own sets of issues in the process.

**Comment by emilyploszaj** [comment] 2024-01-12 23:52
Various performance improvements to crafting, but they rely on some assumptions that break other mods.

**Comment by Xiarno** [comment] 2024-01-13 12:51
> Various performance improvements to crafting, but they rely on some assumptions that break other mods.

Is it worth removing or the performence improvement are just that good?

**Comment by emilyploszaj** [comment] 2024-01-13 18:44
Worth testing both. Craft to inventory is way too important for my productivity so I'd always go for it
