### ISSUE TITLE
No information is displayed when viewing some generic recipes

### ISSUE THREAD

**Issue by Dr-WeiAL** [emilyploszaj/emi#324] opened 2023-10-04 17:15 UTC
The normal situation is as follows
![image](https://github.com/emilyploszaj/emi/assets/47446553/84cabdbe-832f-48e0-bf79-d81d004be75d)

The questions are as follows
![image](https://github.com/emilyploszaj/emi/assets/47446553/400221b3-9c61-456e-9927-30b5620e5022)
For example, the recipe for Farmer's Delight's Cooking Pot
A lot of generic recipes with markers in the upper left corner don't show any information, and there are also items that don't show any information after showing certain items while scrolling

**Comment by emilyploszaj** [comment] 2023-10-05 00:08
This is odd, can you upload a log from when you encounter these issues? I'm curious if there are any errors being thrown.

**Comment by KuryKat** [comment] 2023-10-05 16:32
I will be honest that I encountered those a lot since I started using EMI, but I just assumed it was "normal" lol

**Comment by KuryKat** [comment] 2023-10-05 16:35
Another Example (With Botania included):

![image](https://github.com/emilyploszaj/emi/assets/57152799/070598b9-873b-4c50-9e2d-a34b9765a65f)

![image](https://github.com/emilyploszaj/emi/assets/57152799/87d4e5ba-4f22-478e-9091-64b1b4343103)

Then when you click on it:

![image](https://github.com/emilyploszaj/emi/assets/57152799/db962cf9-2b85-4bf0-b606-7f382c973361)

**Comment by Bluberry-Kat** [comment] 2023-10-05 16:39
do you have logs from when this was occurring?

**Comment by KuryKat** [comment] 2023-10-05 16:39
From what I understood this happens when a Recipe is defined with an array of possible ingredients, instead of a tag

From the above example: [Check This File](https://github.com/VazkiiMods/Botania/blob/b4f47b56ad9f6aae1bf93ce5bdc1f28d331ec9cd/Xplat/src/generated/resources/data/botania/recipes/mushroom_stew.json#L4)

**Comment by Dr-WeiAL** [comment] 2023-10-05 16:42
Oh I'm still troubleshooting what mod is causing this, are you guys close to figuring out the cause already?

**Comment by KuryKat** [comment] 2023-10-05 16:44
> Oh I'm still troubleshooting what mod is causing this, are you guys close to figuring out the cause already?

Check the comment above yours

**Comment by Dr-WeiAL** [comment] 2023-10-05 16:50
> > Oh I'm still troubleshooting what mod is causing this, are you guys close to figuring out the cause already?
> 
> Check the comment above yours

Well, it looks like you found the reason. Thanks.
Then I guess I don't need to say anything.

**Comment by Bluberry-Kat** [comment] 2023-10-05 16:54
@KuryKat please do not spread misinformation in our repo. i understand the desire to help but at-best you have repeated already known information, and at-worst you are actively getting in the way of the issue being resolved.

@Dr-WeiAL i tried to reproduce this in vanilla and failed. i think one of your mods is modifying the function of tooltips. please figure out which it is and report to them. (or send a log, like you were asked to...)
![image](https://github.com/emilyploszaj/emi/assets/20749209/931608a4-bdd7-4360-bd9c-f36d0da1898a)

**Comment by Dr-WeiAL** [comment] 2023-10-05 17:00
> @KuryKat please do not spread misinformation in our repo. i understand the desire to help but at-best you have repeated already known information, and at-worst you are actively getting in the way of the issue being resolved.
> 
> @Dr-WeiAL i tried to reproduce this in vanilla and failed. i think one of your mods is modifying the function of tooltips. please figure out which it is and report to them. (or send a log, like you were asked to...) ![image](https://user-images.githubusercontent.com/20749209/272982088-931608a4-bdd7-4360-bd9c-f36d0da1898a.png)

Well I was checking which mod was causing the problem until just now, and when I saw his confident reply I thought he had found the issue
I'll keep checking mods then

**Comment by KuryKat** [comment] 2023-10-05 17:11
> @KuryKat please do not spread misinformation in our repo. i understand the desire to help but at-best you have repeated already known information, and at-worst you are actively getting in the way of the issue being resolved.
> 
> @Dr-WeiAL i tried to reproduce this in vanilla and failed. i think one of your mods is modifying the function of tooltips. please figure out which it is and report to them. (or send a log, like you were asked to...) ![image](https://user-images.githubusercontent.com/20749209/272982088-931608a4-bdd7-4360-bd9c-f36d0da1898a.png)

I'm sorry, didn't mean it that way, I was just somewhat sure that it was that since in all my tests with EMI, even on small instances, that happened, hence why I even mentioned that I thought it worked that way, my bad :(

**Comment by Dr-WeiAL** [comment] 2023-10-05 17:55
I found the problem, it was caused by LegendaryTooltips
[latest.log](https://github.com/emilyploszaj/emi/files/12821679/latest.log)

**Comment by emilyploszaj** [comment] 2023-10-08 04:12
Since this has been opened elsewhere and is not something EMI can fix, I'll close this issue.

**Closed as completed by emilyploszaj** 2023-10-08 04:12 UTC
Labels: euclid
