### ISSUE TITLE
Cobblemon Potion Recipes not displayed in EMI (with JEI installed as well)

### ISSUE THREAD

**Issue by Burgersim** [emilyploszaj/emi#557] opened 2024-05-29 08:40 UTC
Hi, just wanted to bring this to our attention. Potion recipes from Cobblemon don't seem to be displayed by EMI. Apperently according to a cobblemon dev it might be because they don't produce bottle or potion items? Not sure if that is true tho. it does seem to work in some other Item mods, so maybe EMI is just doing something differently in the way it looks for potion recipes?

I'll add a picture as an example what should be possible and visible in EMI. The recipes do work in game btw, they are just not displayed by EMI.

![grafik](https://github.com/emilyploszaj/emi/assets/26793150/744897ab-abc8-4aff-bde6-23c6200cba69)
![grafik](https://github.com/emilyploszaj/emi/assets/26793150/a5e9b210-3a5f-4524-9080-2c7e8a2b7ef9)
![grafik](https://github.com/emilyploszaj/emi/assets/26793150/418c302f-c87d-4797-9130-7588bca66ef9)

Not sure where the "fault" actually lies tho, cobblemon dev wasn't sure either and suggested it might be with both mods, so I thought maybe I could at least kinda "raise awareness"? ^^*

**Comment by emilyploszaj** [comment] 2024-06-05 03:50
This is peculiar, it may be something to do with the non-potion situation, though I'm unsure what, will need to dig deeper.

**Comment by DaftHunk** [comment] 2024-07-21 15:27
Hello, I had the same problem with all kind of potions 
I resolved it by change the index source to Creative + Registered

**Comment by baebypowder** [comment] 2024-10-21 20:36
Was there any solution to this? I don't want to make a new issue post if this is still an ongoing issue and unresolved

**Comment by emilyploszaj** [comment] 2024-11-01 02:38
This is caused by Cobblemon creating their own implementation of `IBrewingRecipe` instead of using the built in neoforge `BrewingRecipe` and can be fixed by them https://gitlab.com/cable-mc/cobblemon/-/blob/main/neoforge/src/main/kotlin/com/cobblemon/mod/neoforge/brewing/CobblemonNeoForgeBrewingRegistry.kt?ref_type=heads

**Closed as completed by emilyploszaj** 2024-11-01 02:38 UTC
Labels: safe

**Comment by cyberdragon442** [comment] 2025-12-03 23:38
You really need to add support for this to your side. We the pack creators don't want to ask every mod under the sun to use base brewing support to work with EMI when JEI already works just fine. This affects EVERY mod that adds a non-drinkable/non-potion effect item with a brewing stand recipe (I already have issues with Dynamic Trees and Butchery in a less than 200 mod pack).

EDIT: Yes, it may have issues displaying cost with this. But we need to be able to show the recipes at all at least JEI style. Maybe even have this only work with JEI installed as a fallback IE recipe not recognized and fallback to JEI display.
