### ISSUE TITLE
Shift + Left mouse button does not work in the crafting menu 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#431] opened 2024-02-07 12:06 UTC
**It is impossible to quickly remove objects through shift + left-click**
![image](https://github.com/emilyploszaj/emi/assets/106809386/213c1dd5-0396-4699-9d6b-2e5be5dc2f5a)

**Comment by emilyploszaj** [comment] 2024-02-08 01:22
This is a duplicate of #426 which will be fixed in the next update

**Closed as completed by emilyploszaj** 2024-02-08 01:22 UTC

**Comment by Krimatoria** [comment] 2024-02-08 12:04
> This is a duplicate of #426 which will be fixed in the next update

Nice))))
