### ISSUE TITLE
Incompatible with Fabrication's "old tooltips" option

### ISSUE THREAD

**Issue by Octelly** [emilyploszaj/emi#108] opened 2022-12-05 14:12 UTC
[Fabrication](https://modrinth.com/mod/fabrication) is a Minecraft mod that adds a whole bunch of togglable features. There's a feature in the "What's Old Is New Again Extra" section called "Old Tooltip". EMI seems to recognise these tooltips as obstructions, thus as soon as you hover over an item in the list, EMI moves to make space for the tooltip. Moving your cursor from right to left slowly shrinks the item list until it disappears completely.

![image](https://user-images.githubusercontent.com/29976879/205657605-db8cafba-de4c-48c5-81eb-a30f1c9f1787.png)
![image](https://user-images.githubusercontent.com/29976879/205657665-0fae90b2-8681-48e7-99db-9a0c0d982a63.png)
![image](https://user-images.githubusercontent.com/29976879/205657718-65fcb0fd-7b19-4beb-960e-3e077004c05b.png)

**Comment by emilyploszaj** [comment] 2022-12-06 00:56
Duplicate of an old bug that was fixed both in newest Fabrication and EMI 0.5.0

**Closed as completed by emilyploszaj** 2022-12-06 00:56 UTC
