### ISSUE TITLE
EMI cannot create boards from logs. 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [emilyploszaj/emi#430] opened 2024-02-06 23:20 UTC
EMI does not create planks from all logs, creates stripped wood only. This happens with all boards in Regions Unexplored. I haven't checked in vanilla minecraft.

Minecraft 1.19.2
Forge 43.3.5

jei-1.19.2-forge-11.6.0.1018.jar
jeimultiblocks-1.19.2-0.0.3.jar
JustEnoughProfessions-forge-1.19.2-2.0.2.jar
JustEnoughResources-1.19.2-1.2.3.243.jar
emi-1.1.0+1.19.2+forge.jar

![2024-02-07_02 08 39](https://github.com/emilyploszaj/emi/assets/106809386/aa12302f-c5c3-435a-a0e8-4c57ea61ce10)
![2024-02-07_02 08 41](https://github.com/emilyploszaj/emi/assets/106809386/8d0a3b77-dcea-4e17-a1b5-d341fda3a632)
![2024-02-07_02 10 26](https://github.com/emilyploszaj/emi/assets/106809386/428025a9-9291-4ffe-90cc-1feefeb87423)
![2024-02-07_02 12 39](https://github.com/emilyploszaj/emi/assets/106809386/a641490e-2b60-4829-a621-811972fe6745)
![2024-02-07_02 14 06](https://github.com/emilyploszaj/emi/assets/106809386/eba129c9-6043-4ed7-884a-e6dd8123cdc0)
They are created only in the default recipe book mode, while in the window that it creates, and in the EMI window it shows only the recipe. Most likely, the problem is in the recipe book modes. In the rest, they are not created.

![2024-02-07_02 47 09](https://github.com/emilyploszaj/emi/assets/106809386/fe56950b-e245-4f8c-8cd3-71b895df14f7)
![2024-02-07_02 44 25](https://github.com/emilyploszaj/emi/assets/106809386/95106e29-b333-4dfd-8b5d-3104b0a23fca)

**Comment by emilyploszaj** [comment] 2024-02-08 01:23
I believe this is also a duplicate of #426

**Closed as completed by emilyploszaj** 2024-02-08 01:23 UTC

**Comment by Krimatoria** [comment] 2024-02-08 12:05
> I believe this is also a duplicate of #426

I didn't see that there was already such a branch) Ok glad it will be fixed)
