### ISSUE TITLE
EMI experienced a critical exception while reloading, check log

### ISSUE THREAD

**Issue by MCBEModder2020** [emilyploszaj/emi#406] opened 2024-01-07 22:09 UTC
```
[17:06:46] [Thread-80/ERROR] [EMI/]: [EMI] Critical error occured during reload:
java.lang.NullPointerException
[17:06:46] [Thread-80/ERROR] [EMI/]: [EMI] java.lang.NullPointerException
```
compat with https://modrinth.com/mod/destroy?

**Comment by emilyploszaj** [comment] 2024-01-07 23:04
Duplicate of #400, post a full log

**Closed as completed by emilyploszaj** 2024-01-07 23:04 UTC
