### ISSUE TITLE
[BUG] Left Index doesn't update while searching

### ISSUE THREAD

**Issue by Kiryonn** [emilyploszaj/emi#395] opened 2024-01-03 16:03 UTC
| Minecraft | Modloader | Mod
|---|---|---|
| 1.20.1 | Fabric 0.15.3 | 1.0.29 |

![image](https://github.com/emilyploszaj/emi/assets/60699390/44b06bb2-2507-428c-be62-4c3079037d97)

**Comment by emilyploszaj** [comment] 2024-01-03 23:47
Duplicate of #377

**Closed as completed by emilyploszaj** 2024-01-03 23:47 UTC
