### ISSUE TITLE
[Suggestion] Search Box History Scroll

### ISSUE THREAD

**Issue by Quest79** [emilyploszaj/emi#440] opened 2024-02-14 19:44 UTC
I really like EMI and think the work on it has been next level for this mod type. The level of customization is really great too.

Its missing something vital that I (and most players should) use every-time I open jei nei etc. When i click on the search to find an item, they keep a history of the last 10 or 20 searches I made. So all i have to do it click on teh search box, press the up or down key to scroll through past searches. This is an invaluable feature that saves me from typing the same thing 20 times when im going back and forth between different things.

Please consider adding this so i can switch over to this mod from jei. Thank you.

**Comment by emilyploszaj** [comment] 2024-02-18 17:15
This is technically a duplicate of #147, but nevertheless is now implemented in 1.1.2

**Closed as completed by emilyploszaj** 2024-02-18 17:15 UTC
