### ISSUE TITLE
There is no display of Spartan Weaponry Weaponry oil recipe (already installed jei)

### ISSUE THREAD

**Issue by fszsxcylcyl** [emilyploszaj/emi#667] opened 2024-08-15 09:33 UTC
There is no display of Spartan Weaponry Weaponry oil recipe (already installed jei)

Uploading 2024-08-15 17-27-28.mp4…

**Comment by emilyploszaj** [comment] 2024-08-17 02:34
Did you forget to upload a video?

**Comment by fszsxcylcyl** [comment] 2024-08-18 09:05
Uploading 2024-08-15 17-27-28.mp4…

**Comment by fszsxcylcyl** [comment] 2024-08-18 09:07
https://github.com/user-attachments/assets/d0124c54-7e4d-4241-982b-0bdf405995a8

**Comment by fszsxcylcyl** [comment] 2024-08-18 09:30
The recipe for the brewing of weapon oil is not shown.

**Comment by fszsxcylcyl** [comment] 2024-08-18 09:30
The recipe for the brewing of weapon oil is not shown.

**Comment by emilyploszaj** [comment] 2024-08-18 19:51
This video is unplayable, but if this is about brewing recipes, this is a duplicate of #557

**Closed as completed by emilyploszaj** 2024-08-18 19:51 UTC
