### ISSUE TITLE
[Forge 1.0.0-1.19.2] Wonky Tooltips

### ISSUE THREAD

**Issue by BookerCatch** [emilyploszaj/emi#190] opened 2023-05-30 19:47 UTC
Much like Roughly Enough Items, EMI is having issues properly rendering certain tooltips. Namely, tooltips colored by Legendary Tooltips and attribute icons embedded in tooltips added by Quark. Please see below. For clarification, both of these functionalities work fine with JEI, and used to not work with REI (except Quark's attribute icons, which still don't work).

![image](https://github.com/emilyploszaj/emi/assets/43504436/888a4387-58e7-46b2-a014-b35eb7aabbb8)

![image](https://github.com/emilyploszaj/emi/assets/43504436/2fbf512c-7fd7-4b6b-9189-54b1676388bb)

![image](https://github.com/emilyploszaj/emi/assets/43504436/38a5b976-4a5c-49d5-a24a-e110b07172eb)

**Comment by emilyploszaj** [comment] 2023-05-30 22:19
EMI's tooltip system reuses vanilla codepaths at the highest level it can, but due to its requirements of displaying extra information, it is not really possible to go any higher to the raw text levels and above. These incompatibilities are, I imagine, caused by mods targetting too early and only handling pure text rendering from items, and I'm not actually sure if there's anything EMI can do to resolve them.

**Comment by emilyploszaj** [comment] 2023-06-21 00:41
Nope! There was in fact something I could do, at least for the quark tooltips, which were fixed in 1.0.5

**Closed as completed by emilyploszaj** 2023-06-21 00:41 UTC
Labels: safe
