### ISSUE TITLE
EMI appears to search mod IDs by translated name instead of namespace ID

### ISSUE THREAD

**Issue by lummwastaken** [emilyploszaj/emi#347] opened 2023-11-07 02:16 UTC
As seen in the images below, using the '@' tag to search by mod name only accepts search queries using the mod's translated name instead of the mod's unique namespace ID. 

Tested with multiple mods that have differing namespaces/translated names (dustrial_decor, alexsmobs, farmersdelight, etc.)

![2023-11-06_18 06 51](https://github.com/emilyploszaj/emi/assets/132975877/0b11683e-24de-4f6b-bc68-35bab9e6ebeb)
![2023-11-06_18 07 00](https://github.com/emilyploszaj/emi/assets/132975877/16cbcdf9-3f98-4eb2-9d1b-7be6281d94e1)

**Comment by emilyploszaj** [comment] 2023-11-11 20:28
This is the intended behavior at the moment. A future update will likely change this to include mod id.

**Comment by spectrapulse** [comment] 2023-12-01 10:15
Odd and kind of an annoying design choice as it isn't really what you would expect considering other mods that provide a search interface such as AE2 or alternatives to EMI like REI and JEI. Wouldn't it be better to be more consistent and have a behavior close to the norm? I'm quite unsure how to effectively search by Mod ID with the current implementation as pretty much every other mod I've seen and used use namespaces.

**Comment by emilyploszaj** [comment] 2023-12-05 04:05
I looked into it and it turns out EMI has searched by both mod name and mod namespace for several versions.

**Comment by spectrapulse** [comment] 2023-12-08 10:50
> I looked into it and it turns out EMI has searched by both mod name and mod namespace for several versions.

Then maybe I'm just stupid but when I use an `@<namespace_id>` of a mod I expect to see all items of said mod, but instead no results are found. I type the exact same string in JEI and REI and it seems to behave as you would expect. I've looked far and wide to figure out how to simply do this but there seems to be no such functionality in EMI or it is incredibly terribly documented. 

This is either very very poorly documented or said functionality just simply doesn't exist, I've also built from source just to verify that maybe the Modrinth version of the mod is behind or this functionality may exist on a branch but to no success as well. So either this functionality simply doesn't exist, is incredibly poorly documented and may as well be considered non-existent or there has to be some weird loader specific quirk using this just simply doesn't work with in my case Fabric.

Like I genuinely do not intend to sound rude and don't mistake my intentions, but I'm genuinely starting to get frustrated being unable to properly use filters to search through +100 pages of items which seems to be close to impossible using EMI.

**Comment by SiverDX** [comment] 2023-12-08 13:44
if the mod id is "some_mod" you need to search `@some @mod`

**Comment by spectrapulse** [comment] 2023-12-09 00:33
> if the mod id is "some_mod" you need to search `@some @mod`

Okay cool, but the mod id for example Create: Steam 'n' Rails is "railways"
nothing appears when I use `@railways`, shouldn't that work by this logic?

When I search for blocks from Applied Energistics 2, it's mod id is "ae2"
but when I search with `@ae2` results only appear from an addon because it uses `ae2` in its translated name. 

Only being able to search with the translated name of a mod is bad UX, because sometimes mod names for mod addons are long. Sometimes pack devs use a fork as a replacement for another mod for compatibility reasons which uses a name nobody is used to where the as the translated name is changed but not the id. Additionally the only way to find out what the full translated name is, is by using another mod like Mod Menu or Catalogue while searching for a block you know is from one specific mod and happen to be interested in what other blocks it provides which you could do by simply hovering over the result in the results would show you the name of the recipe which includes the namespaced mod id which in REI and JEI you could just put in the search bar and find out what other blocks it provides. Great for when there's compat mods.

But as of now, this isn't possible. Not in the latest mod version on Modrinth, not in a self-compiled version of EMI on said branch which targets said Minecraft version but instead, Just like the OP of the issue has shown it simply doesn't work.

So I don't understand why this issue is closed because even "if it really exists" which I'm pretty sure that it doesn't, it isn't properly documented or does not behave in a way people would expect.

Also if I really am supposed to type `@some @mod` when a **mod id** is `some_mod`, that's kind of dumb and should be changed. But I assume you mean a mod's translated name as I've only seen this work or translated names anyways.

**Comment by emilyploszaj** [comment] 2023-12-09 00:37
You're being relatively heated on a github issue, but you're correct, I closed this because I misread the code and I actually hadn't implemented searching by mod id like I intended to. That'll get fixed soon.

**Comment by spectrapulse** [comment] 2023-12-09 00:49
> You're being relatively heated on a github issue, but you're correct, I closed this because I misread the code and I actually hadn't implemented searching by mod id like I intended to. That'll get fixed soon.

I apologize for sounding rude and kind of heated because I didn't mean to sound like that. But in my defense, I've just been rather frustrated using EMI for this specific reason because other than that it's the greatest mod in what it does. The closure of the issue just hit the wrong string and being used to some developers of mods being rather ignorant, denying problems or straight up couldn't care more or less fixing important issues for reasons such as being on a different *but supported* modding platform than the majority uses just has left a strong bad taste in my mouth. And stuff like that is kind of a pain as a private pack maintainer as having to deal with users which are less experienced or not knowledgeable about the technical side of things and what kind of impact having to replace a single mod can have is just kind of a pain.

**Comment by emilyploszaj** [comment] 2023-12-16 08:03
Sorry for the delay, this was fixed in 1.0.28

**Closed as completed by emilyploszaj** 2023-12-16 08:03 UTC
